# Generated by Django 4.2.16 on 2026-06-21 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reclamos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reclamo_nuevo', 'Reclamo nuevo'), ('reclamo_aceptado', 'Reclamo aceptado'), ('reclamo_rechazado', 'Reclamo rechazado'), ('reclamo_asignado', 'Reclamo asignado'), ('asignacion_nueva', 'Asignación nueva'), ('reclamo_en_atencion', 'Reclamo en atención'), ('reporte_enviado', 'Reporte enviado'), ('reclamo_solucionado', 'Reclamo solucionado'), ('reclamo_no_solucionado', 'Reclamo no solucionado'), ('usuario_nuevo', 'Usuario nuevo')], max_length=40)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('reclamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='reclamos.reclamo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
