# Generated by Django 4.2.16 on 2026-06-07 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reclamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_trabajo', models.TextField()),
                ('resultado', models.CharField(choices=[('solucionado', 'Solucionado'), ('no_solucionado', 'No solucionado'), ('requiere_revision', 'Requiere revisión')], max_length=20)),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='reportes/')),
                ('latitud_atencion', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud_atencion', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='reclamos.reclamo')),
            ],
            options={
                'verbose_name': 'Reporte de trabajador',
                'verbose_name_plural': 'Reportes de trabajador',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
