# Generated by Django 4.2.16 on 2026-06-21 13:17

from django.db import migrations, models


def dividir_nombre_completo(apps, schema_editor):
    """Rellena nombres/apellidos a partir del nombre_completo existente.

    Heurística boliviana: si hay 3+ palabras, las 2 últimas son apellidos;
    si hay 2 palabras, la última es el apellido; si hay 1, todo es nombre.
    Es el mejor esfuerzo para datos antiguos; los casos atípicos se ajustan a
    mano. Los datos demo se regeneran limpios con seed_data.
    """
    Usuario = apps.get_model('usuarios', 'Usuario')
    for usuario in Usuario.objects.all():
        partes = (usuario.nombre_completo or '').split()
        if not partes:
            continue
        if len(partes) >= 3:
            usuario.nombres = ' '.join(partes[:-2])
            usuario.apellidos = ' '.join(partes[-2:])
        elif len(partes) == 2:
            usuario.nombres = partes[0]
            usuario.apellidos = partes[1]
        else:
            usuario.nombres = partes[0]
            usuario.apellidos = ''
        usuario.save(update_fields=['nombres', 'apellidos'])


def revertir(apps, schema_editor):
    # Nada que revertir: el nombre_completo original se conserva intacto.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres'),
        ),
        migrations.RunPython(dividir_nombre_completo, revertir),
    ]
