# Generated by Django 4.2.16 on 2026-06-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('modulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento de bitácora',
                'verbose_name_plural': 'Bitácora',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
