# Generated by Django 4.2.16 on 2026-06-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('estado_asignacion', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada')], default='activa', max_length=20)),
            ],
            options={
                'verbose_name': 'Asignación de reclamo',
                'verbose_name_plural': 'Asignaciones de reclamo',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
