# Generated by Django 4.2.16 on 2026-06-07 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reclamos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionreclamo',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacionreclamo',
            name='reclamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='reclamos.reclamo'),
        ),
        migrations.AddField(
            model_name='asignacionreclamo',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
