# Generated by Django 4.2.16 on 2026-06-07 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría de reclamo',
                'verbose_name_plural': 'Categorías de reclamo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('tipo_comentario', models.CharField(default='general', max_length=50)),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comentario de reclamo',
                'verbose_name_plural': 'Comentarios de reclamo',
                'ordering': ['fecha_comentario'],
            },
        ),
        migrations.CreateModel(
            name='EstadoReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estado de reclamo',
                'verbose_name_plural': 'Estados de reclamo',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='ImagenReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='reclamos/adjuntos/')),
                ('tipo_imagen', models.CharField(choices=[('evidencia', 'Evidencia'), ('atencion', 'Atención')], default='evidencia', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen de reclamo',
                'verbose_name_plural': 'Imágenes de reclamo',
            },
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('direccion_texto', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='reclamos/')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamos', to='reclamos.categoriareclamo')),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Reclamos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
