# Generated by Django 4.2.16 on 2026-06-07 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reclamos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='estado_actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamos', to='reclamos.estadoreclamo'),
        ),
        migrations.AddField(
            model_name='imagenreclamo',
            name='reclamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='reclamos.reclamo'),
        ),
        migrations.AddField(
            model_name='historialestadoreclamo',
            name='estado_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reclamos.estadoreclamo'),
        ),
        migrations.AddField(
            model_name='historialestadoreclamo',
            name='estado_nuevo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reclamos.estadoreclamo'),
        ),
        migrations.AddField(
            model_name='historialestadoreclamo',
            name='reclamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reclamos.reclamo'),
        ),
        migrations.AddField(
            model_name='historialestadoreclamo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentarioreclamo',
            name='reclamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='reclamos.reclamo'),
        ),
        migrations.AddField(
            model_name='comentarioreclamo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
